# Generated by Django 5.1.1 on 2024-10-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_books_overview_alter_books_image'),
        ('students', '0002_alter_students_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_books',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='students.students'),
        ),
    ]
